<a href="https://colab.research.google.com/github/AleksandraJuras2000/Kurs_Udemi/blob/main/02_pandas/01_pandas_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pandas - Intro
Pandas to popularna biblioteka programistyczna w języku Python, która jest używana do manipulacji i analizy danych. Jest to potężne narzędzie, które ułatwia wczytywanie, przekształcanie, eksplorację i analizę danych w formie tabelarycznej, takich jak arkusze kalkulacyjne lub bazy danych.



Główne cechy i funkcje biblioteki Pandas:

### Struktury danych:
Pandas wprowadza dwie główne struktury danych: Series i DataFrame.

### Series:
To jednowymiarowa tablica danych, podobna do kolumny w arkuszu kalkulacyjnym lub kolumny w bazie danych. Series można traktować jako uporządkowany zestaw danych z indeksem.

###DataFrame:
To dwuwymiarowa struktura danych, która przypomina tabelę lub arkusz kalkulacyjny. DataFrame składa się z kolumn i wierszy, a każda kolumna może zawierać różne typy danych.

###Wczytywanie i zapisywanie danych:
Pandas umożliwia wczytywanie danych z różnych źródeł, takich jak pliki CSV, Excel, SQL, JSON i wiele innych. Możesz również zapisywać dane do tych formatów.

###Indeksowanie i selekcja danych:
Pandas oferuje różnorodne mechanizmy indeksowania i selekcji danych, co pozwala na dostęp do konkretnych kolumn, wierszy lub komórek danych w bardzo elastyczny sposób.

###Operacje na danych:
Biblioteka umożliwia wykonywanie różnych operacji na danych, takich jak filtrowanie, sortowanie, grupowanie, łączenie i wiele innych. Możesz także przeprowadzać operacje matematyczne na danych w sposób efektywny.

###Obsługa brakujących danych:
Pandas oferuje narzędzia do radzenia sobie z danymi brakującymi, takie jak usuwanie lub uzupełnianie brakujących wartości.

###Analiza i eksploracja danych:
Biblioteka ułatwia eksplorację danych poprzez obliczanie statystyk opisowych, generowanie wykresów i wizualizacji danych.

###Obsługa szeregów czasowych:
Pandas posiada wsparcie dla operacji na szeregach czasowych, co jest przydatne w analizie danych związanych z czasem.

###Integracja z innymi narzędziami:
Pandas można łatwo łączyć z innymi bibliotekami do analizy danych i uczenia maszynowego, takimi jak NumPy, SciPy, Matplotlib, scikit-learn i wiele innych.

###Wsparcie społeczności:
Pandas posiada aktywną społeczność użytkowników i deweloperów, co oznacza, że istnieje wiele dostępnych źródeł, tutoriali i materiałów do nauki.



Pandas jest nieodzownym narzędziem w dziedzinie analizy danych i jest szeroko stosowany w dziedzinach takich jak nauka danych, analiza biznesowa, badania naukowe i wiele innych. Dzięki swojej prostocie i elastyczności jest bardzo popularny wśród profesjonalistów zajmujących się danymi oraz programistów Pythona.

In [ ]:
import pandas as pd

In [ ]:
pd.__version__

'2.2.2'

### Podstawowe struktury danych: pd.Series

In [ ]:
s = pd.Series(data = [3, 2, 4, 5])  #indeksowanie!
s

0    3
1    2
2    4
3    5
dtype: int64

In [ ]:
s = pd.Series(data = [3, 2, 4, 5], index =['a', 'b', 'c', 'd'], name = 'sample')   #mozemy sami napisac indeksy, mozna uzyc np daty
s

a    3
b    2
c    4
d    5
Name: sample, dtype: int64

In [ ]:
s = pd.Series(data = [3., 2, 4, 5], index =['a', 'b', 'c', 'd'], name = 'sample')  #jesli chociaz jedna z tych wartosci bedzie float to automatycznie calosc zmieni sie na float
s

a    3.0
b    2.0
c    4.0
d    5.0
Name: sample, dtype: float64

In [ ]:
import numpy as np

In [ ]:
s = pd.Series(data = [3., np.nan, 4, 5], index =['a', 'b', 'c', 'd'], name = 'sample')  #BRAKI DANYCH
s
# waże jest to jak zapisujemy dane poniewaz w przypadku liczenia jakis statystyk ta wartosc nie bedzie brana pod uwage

a    3.0
b    NaN
c    4.0
d    5.0
Name: sample, dtype: float64

In [ ]:
s = pd.Series( data = (True, False, False))
s

0     True
1    False
2    False
dtype: bool

In [ ]:
s = pd.Series(data=np.arange(10, 20), index = pd.date_range(start='20200101', periods = 10))  # ZA INDEKS WSTAWIONA DATA
s

2020-01-01    10
2020-01-02    11
2020-01-03    12
2020-01-04    13
2020-01-05    14
2020-01-06    15
2020-01-07    16
2020-01-08    17
2020-01-09    18
2020-01-10    19
Freq: D, dtype: int64

In [ ]:
list(s.index)

[Timestamp('2020-01-01 00:00:00'),
 Timestamp('2020-01-02 00:00:00'),
 Timestamp('2020-01-03 00:00:00'),
 Timestamp('2020-01-04 00:00:00'),
 Timestamp('2020-01-05 00:00:00'),
 Timestamp('2020-01-06 00:00:00'),
 Timestamp('2020-01-07 00:00:00'),
 Timestamp('2020-01-08 00:00:00'),
 Timestamp('2020-01-09 00:00:00'),
 Timestamp('2020-01-10 00:00:00')]

In [ ]:
s.dtype

dtype('int64')

In [ ]:
s = pd.Series(data = ['python', 'java', 'sql'], name = 'languages')
s

0    python
1      java
2       sql
Name: languages, dtype: object

In [ ]:
type(s)

pandas.core.series.Series

In [ ]:
s.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
s.values

array(['python', 'java', 'sql'], dtype=object)

In [ ]:
s.dtypes  # jeslu tekst to zwróci duże O

dtype('O')

In [ ]:
s.shape

(3,)

In [ ]:
price = pd.Series(data = {'Apple': 200, 'CD Projekt': 50, 'Amazon': 1500, 'KGHM': np.nan}) # zastosowany słownik
price

Apple          200.0
CD Projekt      50.0
Amazon        1500.0
KGHM             NaN
dtype: float64

In [ ]:
price['CD Projekt']

50

In [ ]:
#price[1]
price.iloc[1]

50

In [ ]:
price.count()

3

In [ ]:
price.value_counts() # sprawda ile razy powtarzały sie dane wartosci
price.value_counts(dropna=False)  # liczy sie razem z brakami danych

200.0     1
50.0      1
1500.0    1
NaN       1
Name: count, dtype: int64

In [ ]:
price.sum()

1750

In [ ]:
price.max()

1500

In [ ]:
price.min()

50

In [ ]:
price.describe()

count       3.000000
mean      583.333333
std       797.391581
min        50.000000
25%       125.000000
50%       200.000000
75%       850.000000
max      1500.000000
dtype: float64

In [ ]:
price.nlargest(2)  #np. wybierz top dwa elementy

Amazon    1500.0
Apple      200.0
dtype: float64

In [ ]:
price.nsmallest(2)

CD Projekt     50.0
Apple         200.0
dtype: float64

In [ ]:
price.rank()  # porzadkuje obiekt series

Apple         2.0
CD Projekt    1.0
Amazon        3.0
KGHM          NaN
dtype: float64

In [ ]:
price.sort_values()
price.sort_values(ascending = False)

Amazon        1500.0
Apple          200.0
CD Projekt      50.0
KGHM             NaN
dtype: float64

In [ ]:
price_pln = price.apply(lambda x : x * 3.8 ) # apply bierze za argument funkcje, zmiany trzeba przypisac
price_pln

Apple          760.0
CD Projekt     190.0
Amazon        5700.0
KGHM             NaN
dtype: float64

In [ ]:
price

Apple          200.0
CD Projekt      50.0
Amazon        1500.0
KGHM             NaN
dtype: float64

### PODSTAWOWE STRUKTURY DANYCH: pd.DataFrame

In [ ]:
df = pd.DataFrame(data=[12, 12, 32], index = ['first', 'second', 'third'], columns = ['col_1'])
df

        col_1
first      12
second     12
third      32

In [ ]:
df = pd.DataFrame(data={'WIG20': ['PKN ORLEN', 'PKO BP'],
                        'mWIG40': ['Amica', 'Playway']})
df

       WIG20   mWIG40
0  PKN ORLEN    Amica
1     PKO BP  Playway

In [ ]:
df = pd.DataFrame(data=[[100, 132, 332], [232, 323, 111]], index = ['first', 'second'], columns = ['col_1', 'col_2', 'col_3'])
df

        col_1  col_2  col_3
first     100    132    332
second    232    323    111

In [ ]:
df.columns

Index(['col_1', 'col_2', 'col_3'], dtype='object')

In [ ]:
df.index

Index(['first', 'second'], dtype='object')

In [ ]:
df.values

array([[100, 132, 332],
       [232, 323, 111]])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, first to second
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col_1   2 non-null      int64
 1   col_2   2 non-null      int64
 2   col_3   2 non-null      int64
dtypes: int64(3)
memory usage: 172.0+ bytes

In [ ]:
df.describe()

            col_1       col_2       col_3
count    2.000000    2.000000    2.000000
mean   166.000000  227.500000  221.500000
std     93.338095  135.057395  156.270599
min    100.000000  132.000000  111.000000
25%    133.000000  179.750000  166.250000
50%    166.000000  227.500000  221.500000
75%    199.000000  275.250000  276.750000
max    232.000000  323.000000  332.000000

### SELEKCJA KOLUMN

In [ ]:
df

        col_1  col_2  col_3
first     100    132    332
second    232    323    111

In [ ]:
df['col_2'] #zostanie zworcona kolumna, jest to obiekt typu series

first     132
second    323
Name: col_2, dtype: int64

In [ ]:
type(df['col_1'])

pandas.core.series.Series

In [ ]:
df[['col_3']]    # w tym peztpadku wraca nam obiekt data frame a nie series jak w poprzednim przypadu

        col_3
first     332
second    111

In [ ]:
type(df[['col_3']])

pandas.core.frame.DataFrame

In [ ]:
df.columns = ['a', 'b', 'c']
df

          a    b    c
first   100  132  332
second  232  323  111

In [ ]:
df.a # po kropce wpisujemy nazwe kolumny , nie zawsze on bedzie praktyczny i nie zawsze bedzie go mozna zastosowac

first     100
second    232
Name: a, dtype: int64

In [ ]:
df['d'] = df.a + df.c
df

In [ ]:
df = pd.DataFrame(data=[[100, 132, 332], [232, 323, 111]], index = ['first', 'second'], columns = ['col_1', 'col_2', 'col_3'])
df

        col_1  col_2  col_3
first     100    132    332
second    232    323    111

In [ ]:
df.loc['first']  # pozwala wycinac po nazwach

col_1    100
col_2    132
col_3    332
Name: first, dtype: int64

In [ ]:
df.iloc[1]

col_1    232
col_2    323
col_3    111
Name: second, dtype: int64

In [ ]:
df.loc['first', 'col_2']

132

In [ ]:
df.loc[:, 'col_2']

first     132
second    323
Name: col_2, dtype: int64

In [ ]:
df.iloc[:, 2]

first     332
second    111
Name: col_3, dtype: int64